name: 🚀 Deploy Skillflux

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 160.187.169.41
          username: vfstr
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            /data/projects/deploy/deploy.sh